@module=testAccountCreation
Feature: Registration
Description: This feature allows user to create an account

@id=1 @positive
Scenario Outline: Complete registration with valid details from SignIn Page

	Given User access <brand> website
	When User navigate to login page
	And User enters <email> , <password> and register
	And User provide <firstName> , <lastName> , <address> , <apartment> , <city> , <country> , <state> , <zip> , <phone> , <gender> , <bMonth> , <bDay> , <prefCountry> , <prefState> , <prefStore> , <communication> , <type> and save
	Then User should be registered successfully with complete details
	
	
	@brand=PB
	Examples:
	| brand | email                 | password | firstName |lastName| address    | apartment | city        | country       | state      | zip   | phone      | gender | bMonth  | bDay | prefCountry | prefState | prefStore | communication | type |
	| vh  | myaccountvh43@gmail.com  | Passw0rd | myaccount | vh3    | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh44@gmail.com  | Passw0rd | myaccount | vh4    | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh45@gmail.com  | Passw0rd | myaccount | vh5    | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh46@gmail.com  | Passw0rd | myaccount | vh6    | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh47@gmail.com  | Passw0rd | myaccount | vh7    | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh48@gmail.com  | Passw0rd | myaccount | vh8    | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh49@gmail.com  | Passw0rd | myaccount | vh9    | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh410@gmail.com | Passw0rd | myaccount | vh10   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh411@gmail.com | Passw0rd | myaccount | vh11   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh415@gmail.com | Passw0rd | myaccount | vh15   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh416@gmail.com | Passw0rd | myaccount | vh16   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh417@gmail.com | Passw0rd | myaccount | vh17   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh418@gmail.com | Passw0rd | myaccount | vh18   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh419@gmail.com | Passw0rd | myaccount | vh19   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      | 
	| vh  | myaccountvh420@gmail.com | Passw0rd | myaccount | vh20   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh421@gmail.com | Passw0rd | myaccount | vh21   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh422@gmail.com | Passw0rd | myaccount | vh22   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh423@gmail.com | Passw0rd | myaccount | vh23   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh424@gmail.com | Passw0rd | myaccount | vh24   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh425@gmail.com | Passw0rd | myaccount | vh25   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh426@gmail.com | Passw0rd | myaccount | vh26   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh427@gmail.com | Passw0rd | myaccount | vh27   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh428@gmail.com | Passw0rd | myaccount | vh28   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh429@gmail.com | Passw0rd | myaccount | vh29   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh430@gmail.com | Passw0rd | myaccount | vh30   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh431@gmail.com | Passw0rd | myaccount | vh31   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh432@gmail.com | Passw0rd | myaccount | vh32   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh433@gmail.com | Passw0rd | myaccount | vh33   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh434@gmail.com | Passw0rd | myaccount | vh34   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| vh  | myaccountvh435@gmail.com | Passw0rd | myaccount | vh35   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	
	@brand=TH
	Examples:
	| brand | email                   | password | firstName | lastName | address    | apartment | city        | country       | state      | zip   | phone      | gender | bMonth  | bDay | prefCountry   | prefState  | prefStore                                                  | communication | type |
	| TH    | myaccountth43@gmail.com  | Passw0rd | myaccount | th3      | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | nited States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth44@gmail.com  | Passw0rd | myaccount | th4      | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth45@gmail.com  | Passw0rd | myaccount | th5      | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth46@gmail.com  | Passw0rd | myaccount | th6      | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth47@gmail.com  | Passw0rd | myaccount | th7      | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth48@gmail.com  | Passw0rd | myaccount | th8      | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth49@gmail.com  | Passw0rd | myaccount | th9      | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth410@gmail.com | Passw0rd | myaccount | th10     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth411@gmail.com | Passw0rd | myaccount | th11     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth415@gmail.com | Passw0rd | myaccount | th15     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth416@gmail.com | Passw0rd | myaccount | th16     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth417@gmail.com | Passw0rd | myaccount | th17     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth418@gmail.com | Passw0rd | myaccount | th18     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth419@gmail.com | Passw0rd | myaccount | th19     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth420@gmail.com | Passw0rd | myaccount | th20     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth421@gmail.com | Passw0rd | myaccount | th21     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth422@gmail.com | Passw0rd | myaccount | th22     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth423@gmail.com | Passw0rd | myaccount | th23     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth424@gmail.com | Passw0rd | myaccount | th24     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth425@gmail.com | Passw0rd | myaccount | th25     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth426@gmail.com | Passw0rd | myaccount | th26     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth427@gmail.com | Passw0rd | myaccount | th27     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth428@gmail.com | Passw0rd | myaccount | th28     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth429@gmail.com | Passw0rd | myaccount | th29     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth430@gmail.com | Passw0rd | myaccount | th30     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth431@gmail.com | Passw0rd | myaccount | th31     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth432@gmail.com | Passw0rd | myaccount | th32     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth433@gmail.com | Passw0rd | myaccount | th33     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth434@gmail.com | Passw0rd | myaccount | th34     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	| TH    | myaccountth435@gmail.com | Passw0rd | myaccount | th35     | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | January | 12   | United States | New Jersey | Garden State Plaza - 1 Garden State Plaza Way, Paramus, NJ | web           | men  |
	
	@brand=CKUS
	Examples:
	| brand | email                     | password | firstName | lastName | address    | apartment | city        | country       | state      | zip   | phone      | gender | bMonth  | bDay | prefCountry | prefState | prefStore | communication | type |
	| CKUS  | myaccountckus43@gmail.com  | Passw0rd | myaccount | ckus3    | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus44@gmail.com  | Passw0rd | myaccount | ckus4    | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus45@gmail.com  | Passw0rd | myaccount | ckus5    | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus46@gmail.com  | Passw0rd | myaccount | ckus6    | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus47@gmail.com  | Passw0rd | myaccount | ckus7    | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus48@gmail.com  | Passw0rd | myaccount | ckus8    | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus49@gmail.com  | Passw0rd | myaccount | ckus9    | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus410@gmail.com | Passw0rd | myaccount | ckus10   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus411@gmail.com | Passw0rd | myaccount | ckus11   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus415@gmail.com | Passw0rd | myaccount | ckus15   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus416@gmail.com | Passw0rd | myaccount | ckus16   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus417@gmail.com | Passw0rd | myaccount | ckus17   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus418@gmail.com | Passw0rd | myaccount | ckus18   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus419@gmail.com | Passw0rd | myaccount | ckus19   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      | 
	| CKUS  | myaccountckus420@gmail.com | Passw0rd | myaccount | ckus20   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus421@gmail.com | Passw0rd | myaccount | ckus21   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus422@gmail.com | Passw0rd | myaccount | ckus22   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus423@gmail.com | Passw0rd | myaccount | ckus23   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus424@gmail.com | Passw0rd | myaccount | ckus24   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus425@gmail.com | Passw0rd | myaccount | ckus25   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus426@gmail.com | Passw0rd | myaccount | ckus26   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus427@gmail.com | Passw0rd | myaccount | ckus27   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus428@gmail.com | Passw0rd | myaccount | ckus28   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus429@gmail.com | Passw0rd | myaccount | ckus29   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus430@gmail.com | Passw0rd | myaccount | ckus30   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus431@gmail.com | Passw0rd | myaccount | ckus31   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus432@gmail.com | Passw0rd | myaccount | ckus32   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus433@gmail.com | Passw0rd | myaccount | ckus33   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus434@gmail.com | Passw0rd | myaccount | ckus34   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKUS  | myaccountckus435@gmail.com | Passw0rd | myaccount | ckus35   | 1200 US Highway 22 |           | Bridgewater | United States | New Jersey | 08807 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	
	@brand=CKCA
	Examples:
	| brand | email                     | password | firstName | lastName | address               | apartment | city    | country | state   | zip     | phone      | gender | bMonth  | bDay | prefCountry | prefState | prefStore | communication | type |
	| CKCA  | myaccountckca43@gmail.com  | Passw0rd | myaccount | ckca3    | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca44@gmail.com  | Passw0rd | myaccount | ckca4    | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca45@gmail.com  | Passw0rd | myaccount | ckca5    | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca46@gmail.com  | Passw0rd | myaccount | ckca6    | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca47@gmail.com  | Passw0rd | myaccount | ckca7    | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca410@gmail.com | Passw0rd | myaccount | ckca10   | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca411@gmail.com | Passw0rd | myaccount | ckca11   | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca415@gmail.com | Passw0rd | myaccount | ckca15   | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca416@gmail.com | Passw0rd | myaccount | ckca16   | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |		
	| CKCA  | myaccountckca417@gmail.com | Passw0rd | myaccount | ckca17   | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca418@gmail.com | Passw0rd | myaccount | ckca18   | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca428@gmail.com | Passw0rd | myaccount | ckca28   | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca429@gmail.com | Passw0rd | myaccount | ckca29   | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca430@gmail.com | Passw0rd | myaccount | ckca30   | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca431@gmail.com | Passw0rd | myaccount | ckca31   | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca432@gmail.com | Passw0rd | myaccount | ckca32   | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca433@gmail.com | Passw0rd | myaccount | ckca33   | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca434@gmail.com | Passw0rd | myaccount | ckca34   | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	| CKCA  | myaccountckca435@gmail.com | Passw0rd | myaccount | ckca35   | 6730 University Drive |           | Lacombe | Canada  | Alberta | T4L 2E5 | 6094065792 | Male   | 1       | 1    |             |           |           |               |      |
	
	@brand=SPEEDO
	Examples:
	| brand  | email                       | password | firstName | lastName | address    | apartment | city | country | state | zip | phone | gender | bMonth | bDay | prefCountry | prefState | prefStore | communication | type |
	| SPEEDO | myaccountspeedo43@gmail.com  | Passw0rd | myaccount | speedo3  |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo44@gmail.com  | Passw0rd | myaccount | speedo4  |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo45@gmail.com  | Passw0rd | myaccount | speedo5  |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo46@gmail.com  | Passw0rd | myaccount | speedo6  |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo47@gmail.com  | Passw0rd | myaccount | speedo7  |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo49@gmail.com  | Passw0rd | myaccount | speedo9  |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo411@gmail.com | Passw0rd | myaccount | speedo11 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo416@gmail.com | Passw0rd | myaccount | speedo16 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo417@gmail.com | Passw0rd | myaccount | speedo17 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo419@gmail.com | Passw0rd | myaccount | speedo19 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo420@gmail.com | Passw0rd | myaccount | speedo20 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo421@gmail.com | Passw0rd | myaccount | speedo21 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo422@gmail.com | Passw0rd | myaccount | speedo22 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo423@gmail.com | Passw0rd | myaccount | speedo23 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo424@gmail.com | Passw0rd | myaccount | speedo24 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo425@gmail.com | Passw0rd | myaccount | speedo25 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo426@gmail.com | Passw0rd | myaccount | speedo26 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo427@gmail.com | Passw0rd | myaccount | speedo27 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo428@gmail.com | Passw0rd | myaccount | speedo28 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo429@gmail.com | Passw0rd | myaccount | speedo29 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo430@gmail.com | Passw0rd | myaccount | speedo30 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |
	| SPEEDO | myaccountspeedo431@gmail.com | Passw0rd | myaccount | speedo31 |            |           |      |         |       |     |       |        |        |      |             |           |           |               |      |