package com.qualitest.pvh.runner;

import cucumber.api.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import org.junit.runner.RunWith;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(features= {
			//	"src/test/resources/features/Registration_Login_Module/LoginPB.feature",
			//	"src/test/resources/features/Registration_Login_Module/LoginCK.feature",
				//"src/test/resources/features/Registration_Login_Module/LoginCKCA.feature",
			//	"src/test/resources/features/Registration_Login_Module/LoginTH.feature",
			//	"src/test/resources/features/Registration_Login_Module/LoginSP.feature",
			//	"src/test/resources/features/Registration_Login_Module/RegistrationPB.feature",
			//	"src/test/resources/features/Registration_Login_Module/RegistrationCK.feature",
			//	"src/test/resources/features/Registration_Login_Module/RegistrationCKCA.feature",
			//	"src/test/resources/features/Registration_Login_Module/RegistrationTH.feature",
			//	"src/test/resources/features/Registration_Login_Module/RegistrationSP.feature",
//				"src/test/resources/features/Registration_Login_Module/ForgotPassword.feature",
			//	"src/test/resources/features/Registration_Login_Module/TestAccountCreation.feature",
//				"src/test/resources/features/Checkout_Module/Checkout.feature",
			//	"src/test/resources/features/Checkout_Module/CheckoutPB.feature",
			//	"src/test/resources/features/Checkout_Module/CheckoutCK.feature",
			//	"src/test/resources/features/Checkout_Module/CheckoutTH.feature",
			//	"src/test/resources/features/Checkout_Module/CheckoutSP.feature",
/*				"src/test/resources/features/Checkout_Module/ModifyOrder.feature",
				"src/test/resources/features/MyAccount_Module/MyAccountCK.feature",
				"src/test/resources/features/MyAccount_Module/MyAccountPB.feature",
				"src/test/resources/features/MyAccount_Module/MyAccountSP.feature",
				"src/test/resources/features/MyAccount_Module/MyAccountTH.feature",*/
			//	"src/test/resources/features/MyAccount_Module/MyAccountCKAddressyOn.feature",
			//	"src/test/resources/features/MyAccount_Module/MyAccountCKCAAddressyOn.feature",
			//	"src/test/resources/features/MyAccount_Module/MyAccountPBAddressyOn.feature",
			//	"src/test/resources/features/MyAccount_Module/MyAccountTHAddressyOn.feature",
			//	"src/test/resources/features/MyAccount_Module/MyAccountSPAddressyOn.feature",
			//	"src/test/resources/features/Search_Filter_Module/SearchCK.feature",
			//	"src/test/resources/features/Search_Filter_Module/SearchCKCA.feature",
			//	"src/test/resources/features/Search_Filter_Module/SearchPB.feature",
			//	"src/test/resources/features/Search_Filter_Module/SearchSP.feature",
			//	"src/test/resources/features/Search_Filter_Module/SearchTH.feature",
			//	"src/test/resources/features/Search_Filter_Module/FilterSortProductCK.feature",
			//	"src/test/resources/features/Search_Filter_Module/FilterSortProductCKCA.feature",
			//	"src/test/resources/features/Search_Filter_Module/FilterSortProductPB.feature",
			//	"src/test/resources/features/Search_Filter_Module/FilterSortProductSP.feature",
			//	"src/test/resources/features/Search_Filter_Module/FilterSortProductTH.feature",
/*				"src/test/resources/features/OrderSubmission_Module/OrderSubmission.feature",
				"src/test/resources/features/Navigation_Module/Navigation.feature",
				"src/test/resources/features/Navigation_Module/NavigationCK.feature",
				"src/test/resources/features/Navigation_Module/NavigationPB.feature",
				"src/test/resources/features/Navigation_Module/NavigationSP.feature",
				"src/test/resources/features/Navigation_Module/NavigationTH.feature",
				"src/test/resources/features/Navigation_Module/Footer.feature",*/
			//	"src/test/resources/features/Cart_Module/BagCartTH.feature",
			//	"src/test/resources/features/Cart_Module/BagCartCK.feature",
			//	"src/test/resources/features/Cart_Module/BagCartCKCA.feature",
			//	"src/test/resources/features/Cart_Module/BagCartSP.feature",
			//	"src/test/resources/features/Cart_Module/BagCartPB.feature",
//				"src/test/resources/features/Cart_Module/Promotions.feature",
//				"src/test/resources/features/Cart_Module/Loyalty.feature",
			//	"src/test/resources/features/Wishlist_Module/WishlistCK.feature",
			//	"src/test/resources/features/Wishlist_Module/WishlistCKCA.feature",
			//	"src/test/resources/features/Wishlist_Module/WishlistPB.feature",
//				"src/test/resources/features/Wishlist_Module/WishlistSP.feature",
			//	"src/test/resources/features/Wishlist_Module/WishlistTH.feature",
			//	"src/test/resources/features/Email_Module/MarketingEmail.feature"	
			//	"src/test/resources/features/SmokeTest_Module/SmokeTest.feature"	
				"src/test/resources/features/Registration_Login_Module/LoginPBMobile.feature",
				"src/test/resources/features/Registration_Login_Module/LoginCKMobile.feature",
				"src/test/resources/features/Registration_Login_Module/LoginTHMobile.feature",
				"src/test/resources/features/Registration_Login_Module/LoginSPMobile.feature",
			"src/test/resources/features/Registration_Login_Module/RegistrationPBMobile.feature",
			"src/test/resources/features/Registration_Login_Module/RegistrationCKMobile.feature",
				"src/test/resources/features/Registration_Login_Module/RegistrationTHMobile.feature",
				"src/test/resources/features/Registration_Login_Module/RegistrationSPMobile.feature",
 			    "src/test/resources/features/Checkout_Module/CheckoutPBMobile.feature",
				"src/test/resources/features/Checkout_Module/CheckoutCKMobile.feature",
				"src/test/resources/features/Checkout_Module/CheckoutTHMobile.feature",
				"src/test/resources/features/Checkout_Module/CheckoutSPMobile.feature",
				"src/test/resources/features/MyAccount_Module/MyAccountCKAddressyOnMobile.feature",
				"src/test/resources/features/MyAccount_Module/MyAccountPBAddressyOnMobile.feature",
				"src/test/resources/features/MyAccount_Module/MyAccountTHAddressyOnMobile.feature",
				"src/test/resources/features/MyAccount_Module/MyAccountSPAddressyOnMobile.feature",
   			    "src/test/resources/features/Search_Filter_Module/SearchCKMobile.feature",
				"src/test/resources/features/Search_Filter_Module/SearchPBMobile.feature",
				"src/test/resources/features/Search_Filter_Module/SearchSPMobile.feature",
				"src/test/resources/features/Search_Filter_Module/SearchTHMobile.feature",
		//	    "src/test/resources/features/MyAccount_Module/MyAccountCKMobile.feature",
		//		"src/test/resources/features/MyAccount_Module/MyAccountPBMobile.feature",
		//		"src/test/resources/features/MyAccount_Module/MyAccountSPMobile.feature",
		//		"src/test/resources/features/MyAccount_Module/MyAccountTHMobile.feature",
				"src/test/resources/features/Search_Filter_Module/FilterSortProductCKMobile.feature",
				"src/test/resources/features/Search_Filter_Module/FilterSortProductPBMobile.feature",
				"src/test/resources/features/Search_Filter_Module/FilterSortProductSPMobile.feature",
				"src/test/resources/features/Search_Filter_Module/FilterSortProductTHMobile.feature",
				"src/test/resources/features/Cart_Module/BagCartTHMobile.feature",
				"src/test/resources/features/Cart_Module/BagCartCKMobile.feature",
				"src/test/resources/features/Cart_Module/BagCartSPMobile.feature",
				"src/test/resources/features/Cart_Module/BagCartPBMobile.feature",
				"src/test/resources/features/Wishlist_Module/WishlistCKMobile.feature",
				"src/test/resources/features/Wishlist_Module/WishlistPBMobile.feature",
				"src/test/resources/features/Wishlist_Module/WishlistTHMobile.feature",
		//		"src/test/resources/features/StoreLocator_Module/StoreLocator.feature",
				},
		glue = {"com.qualitest.pvh.teststeps","com.qualitest.pvh.hooks"}
		)
public class TestRunner {}  